version: "3.9"

services:
  contract-analysis:
    build: .
    container_name: contract-analysis
    ports:
      - "8080:8080"
    environment:
      - OPEN_AI_API_KEY=${OPEN_AI_API_KEY}
    volumes:
      - ./data:/app/data